a1.out:
	gcc ch1-lab1/source/Main.c

a2.out:
	gcc ch1-lab2/source/* ch1-lab2/include/*

a3.out:
	gcc ch1-lab3/source/*

lab1: a1.out
	bash lab1.sh

lab2: a2.out
	bash lab2.sh

lab3: a3.out
	bash lab3.sh
